### ISSUE TITLE
Is not working in Ubuntu 16.10

### ISSUE THREAD

**Issue by cleitondomazak** [ivelkov/teams-for-linux#1]
Hi,

I installed using deb package, and I type the e-mail, and after press tab, try connect automatic, but the screen stay blank on "Sign in to your account".

![screenshot from 2017-02-07 08-39-14](https://cloud.githubusercontent.com/assets/8502873/22687884/0bdf12a8-ed11-11e6-8971-cf5106608397.png)

Some dependency is missing? Or environment configuration?

**Comment by ivelkov** [comment]
I'm using teams at work on a daily basis and I've stumbled upon this issue a few times.
It happens when I'm either not authenticated to the firewall or when my connection has been suddenly interrupted.

I usually fix it by: 
1. Fixing the connection problem
2. Quit teams, start again

I guess what we can do here is add a little tray icon with a refresh/quit menu item.
Does this sound good?

**Comment by cleitondomazak** [comment]
With your explain, I believe that my problem is exactly the firewall or proxy server. I'll verify with infra that could be done, and I update the issue with results.

tks for now.

**Comment by ivelkov** [comment]
Sure, you can also try the Refresh context menu action from the tray icon

**Comment by ivelkov** [comment]
I'm closing this one due to inactivity.
Thanks
